# Makefile for osd and tv
obj-$(CONFIG_AMLOGIC_VOUT)		+= vout/
obj-$(CONFIG_AM_GE2D)			+= ge2d/
obj-$(CONFIG_FB_AM)			+= osd/
obj-$(CONFIG_AM_FB_EXT)			+= osd_ext/
obj-y					+= lcd/
obj-y					+= backlight/
obj-$(CONFIG_AM_LOGO)			+= aml_logo/
obj-$(CONFIG_AMLOGIC_VOUT2)		+= vout2/


