#
# Makefile for Amlogic LCD Drivers
#

obj-y					+= lcd_notify.o
obj-$(CONFIG_AML_LCD_TV)		+= aml_lcd_tv.o
obj-$(CONFIG_AML_LCD_TV)		+= aml_tv_lcd_port/
obj-$(CONFIG_AML_LCD_EXTERN)		+= aml_lcd_extern/
